sudo: true
dist: trusty
install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo
script:
  - "/snap/bin/hugo -v"
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  keep-history: true
  github_token:
    secure: qQldStFg26cK9UyM6V7zUbmSGj5XLmr/63+Pd291kgXK0YveZ6VZ99FT863CEFW/CaZiqUQ5fwDwPeKiB3oYIvPCFkC7N7HsG2LfY3G3saCMhDVB5sHsaKnkILyKRnbkYWRHeIniQMW+od7tz62CeDzX7lhhQXV0uKLx9YQlR+LSUdro5BBzeRaYbP7JVpnnEJte1zsN9g5g6sEHiVrx086vP1h195MpYHg8ZYI5fI0zVmMsjhF3njbqYytUNXB3zfrpB+fvJRvp1iSq6TEv30bnKR/aHden2LEEgwgw2pIzwT2SQPcI5WWv1DD/GK1Odt7U2/64gLciHkwI8MKkZEmtva6+s4bheNfLrHYMCrjwJDGB98NwVYCU2UD0+BXtXlccvZUyJ9SJOr9AaSII1s6+i/g6MtPJIJwHywgDFPh4dkRvI5/q+r8Wud2xmukapeJsJNC9H1pWzx9rsqR3gmtbYlpurJXrfDibYYSBH5tjVPNq4hryBTdLlmiQCxTjAwmj4M89g9Mra7bFfzXUM0OqqSL+EIzXawBmug88NhjH1RDnYCjHa7TVO9SZ+2zlUHiLytCoIxKkUciowLu+gyaDEFU3Isj5C8PkpaFUwf+J+8u5t7i9oU7lgF5CMlNG5N0PjSroztB2Pbn/z9vu9dbax8tZYLbzkrbu9BuBpNs=
  on:
    branch: master
notifications:
  on_success: change
  on_failure: always
